sonar.projectKey=trsenna-garden_vessel-2602-ci-node
sonar.organization=trsenna-garden

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*.test.js

sonar.exclusions=**/node_modules/**, **/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
