name: vessel-2602-ci-node-workflow

on:
  pull_request:
    branches:
      - feature/*

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: yarn install

      - name: Execute tests
        run: yarn test
